pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'NeoForged'
			url = 'https://maven.neoforged.net/releases'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'entity-capture'

include 'fabric-1.21'
include 'neoforge-1.21'
