modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/yunfang1718128/entity-capture/issues"

[[mods]]
modId = "entity_capture"
version = "${version}"
displayName = "Entity Capture"
description = '''Capture any entity (including modded) into a native-resolution .mcvox voxel file for mc-block-studio.'''
authors = "yunfang"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "entity-capture.mixins.json"

[[dependencies.entity_capture]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.entity_capture]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "CLIENT"

[features.entity_capture]
javaVersion = "[21,)"
